# Generated by Django 3.1.7 on 2021-04-26 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='telephone',
            field=models.CharField(default=213, max_length=12),
            preserve_default=False,
        ),
    ]
