# Generated by Django 3.1.7 on 2021-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='own',
            new_name='owner',
        ),
    ]
