# Generated by Django 3.1.7 on 2021-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210328_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image_products/no_img.png', upload_to='image_products/%Y/%d/%m'),
        ),
    ]
