# Generated by Django 3.1.7 on 2021-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210506_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
