# Generated by Django 3.1.7 on 2021-05-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210506_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'default_related_name': 'shop', 'ordering': ('shop',)},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop',
        ),
    ]
