# Generated by Django 3.1.7 on 2021-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210506_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'default_related_name': 'shop', 'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop',
            new_name='name',
        ),
    ]
